### ISSUE TITLE
Link to blog 1 is not working

### ISSUE THREAD

**Issue by sbhatta-aps** [integrtr/guide-to-abap-rap-tutorial#1]
HI,

thanks for the wonderful blogs and detailed explanation. I have noticed that link to blog 1 is not working. could you please look into that?

**Comment by nitish-mehta** [comment]
Thanks for pointing it out. @sbhatta-aps . 
This has been fixed & you will be able to see it here now: https://integrtr.com/guide-to-abap-rap-part1/
